version: "3.9"
services:
  db:
    image: mysql:8.0
    command: >-
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bs_db
      MYSQL_USER: bs_user
      MYSQL_PASSWORD: bs_pass_123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/10_schema.sql:ro
      - ./server:/app
      - uploads_data:/app/uploads 
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 40
volumes:
  uploads_data:
  dbdata:
